# Generated by Django 4.1.5 on 2023-05-02 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DoubtApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messges', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('confirmation', models.IntegerField(default=0)),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
                ('students_ids', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
