# Generated by Django 4.1.5 on 2023-05-02 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0001_initial'),
        ('DoubtApp', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='message_stud',
        ),
    ]
