# Generated by Django 4.1.5 on 2023-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtApp', '0003_rename_message_message_stud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_stud',
            name='messges',
        ),
        migrations.AddField(
            model_name='message_stud',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
