# Generated by Django 4.1.5 on 2023-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
